api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)


app_name = 'api'

urlpatterns = [
    path('products/', views.ProductViewAPIView.as_view(), name='api_products'),
    path('', include(router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('orders/', views.AllOrderViewAPIView.as_view(), name='api_orders'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('detail/', views.detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_quantity/', views.update_quantity, name='update_quantity'),
    path('remove/', views.remove_item, name='remove_item'),

]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'

urlpatterns = [
    path('phone_verification/', views.phone_verification, name='phone_verification'),
    path('code_verification/', views.code_verification, name='code_verification'),
    path('create_order/', views.create_order, name='create_order'),
    path('request/', views.send_request, name='request'),
    path('verify/', views.verify, name='verify'),
]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:category_slug>/', views.index, name='index_by_slug'),
    path('<slug:slug>/<int:id>/', views.product_detail, name='product_detail'),
]

shopproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('api/', include('api.urls', namespace='api')),
    path('order/', include('orders.urls', namespace='orders')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from cart.cart import Cart
from shop.models import Product


@require_POST
def add_to_cart(request, product_id):
    try:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.add(product)
        context = {
            'item_count': len(cart),
            'total_price': cart.get_total_price(),
        }
        return JsonResponse(context)
    except:
        return JsonResponse({"error": "invalid request"})



def detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

@require_POST
def update_quantity(request):
    item_id = request.POST.get('itemId')
    action = request.POST.get('action')
    try:
        product = get_object_or_404(Product, id=item_id)
        cart = Cart(request)
        if action == 'add':
            cart.add(product)
        elif action == 'decrease':
            cart.decrease(product)
        context = {
            'item_count': len(cart),
            'total_price': cart.get_total_price(),
            'quantity': cart.cart[item_id]['quantity'],
            # 'price': cart.cart[item_id]['price'],
            'total': cart.cart[item_id]['quantity'] * cart.cart[item_id]['price'],
            'final_price': cart.get_final_price(),
            'success': True,
        }
        return JsonResponse(context)
    except:
        return JsonResponse({'success': False, 'error': 'Item not found! '})


def remove_item(request):
    product_id = request.GET.get('itemId')
    product = get_object_or_404(Product, id=product_id)
    cart = Cart(request)
    cart.remove(product)
    context = {
        'item_count': len(cart),
        'total_price': cart.get_total_price(),
        'final_price': cart.get_final_price(),
        'success': True,
    }
    return JsonResponse(context)

cart/templates/cart/detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}cart datail{% endblock %}

{% block content %}
<h2>سبد خرید</h2>
<div class="order">

    {% for item in cart %}
        <div class="product-item" data-item-id="{{ item.product.id }}" style="border-style: solid; padding: 5px;">
            <div class="product-info">
                <img style="height: 400px;width: auto;" src="{{ item.product.images.first.image.url }}" alt="image">
                {{ item.product.name }}
            </div>
            <div class="functions" style="border-style: solid; padding: 5px ">
                <div class="quantity-add" >+</div>
                <div class="quantity-decrease">ـ</div>
                <div class="quantity-remove">حذف</div>
            </div>
            <div class="pricec">
                {{ item.product.new_price }}: قیمت محصول
                <p><span id="item-quantity-{{ item.product.id }}">{{ item.quantity }}</span>: تعداد</p>
               <p><span id="item-total-{{ item.product.id }}">{{ item.total }}</span>:قیمت کل</p>

            </div>
        </div>
    {% endfor %}
    <div class="final-prices">
       <p><span id="item-total_price"> {{ cart.get_total_price }}</span> :قیمت کل محصولات</p>
        <div>{{ cart.get_post_price }} :هزینه ارسال</div>
        <p><span id="item-final_price">{{ cart.get_final_price }}</span> :هزینه قابل پرداخت</p>
    </div>
    <h5><a href="{% url 'orders:phone_verification' %}">ادامه</a> </h5>
   <a href="{% url 'shop:index' %}"><h5>بازگشت به لیست محصولات</h5></a>
</div>


 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function(){
            $('.quantity-add').on('click', function(){
                updateQuantity($(this).closest('.product-item').data('item-id'), 'add');
            });
            $('.quantity-decrease').on('click', function (){
                updateQuantity($(this).closest('.product-item').data('item-id'),'decrease');
            });
            $('.quantity-remove').on('click', function(){
            let productId = $(this).closest('.product-item').data('item-id');
            removeItem(productId);
        });

        // Function to update item quantity
        function updateQuantity(itemId, action){
            $.ajax({
                type: "POST",
                url: '{% url "cart:update_quantity" %}', // Ensure correct URL name in Django
                data: {
                    'itemId': itemId, // Fix variable case
                    'action': action,
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                    success: function(response){
                        if (response.success){
                            $('#item_count').text(response.item_count);
                            $('#total_price').text(response.total_price);
                            $('#item-quantity-' + itemId).text(response.quantity);
                            $('#item-total-' + itemId).text(response.total);
                            $('#item-total_price').text(response.total_price);
                            $('#item-final_price').text(response.final_price);
                        }else {
                            alert('Error updating quantity!');
                        }
                    }
            });
        }
          function removeItem(itemId){
                $.ajax({
                    type:"POST",
                    url : "{% url 'cart:remove_item' %}",
                    data:{
                        'itemId' : itemId,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function(response){
                        if (response.success){
                            $('#item_count').text(response.item_count);
                            $('#total_price').text(response.total_price);
                            $('#item-total_price').text(response.total_price);
                            $('#item-final_price').text(response.final_price);
                            $('.product-item[data-item-id="' + itemId + '"]').remove();
                        }else {
                            alert('Error updating quantity!');
                        }
                    }
                });
            }

        });
    </script>
{% endblock %}