api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)


app_name = 'api'

urlpatterns = [
    path('products/', views.ProductViewAPIView.as_view(), name='api_products'),
    path('', include(router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('orders/', views.AllOrderViewAPIView.as_view(), name='api_orders'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('detail/', views.detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_quantity/', views.update_quantity, name='update_quantity'),
    path('remove/', views.remove_item, name='remove_item'),

]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:category_slug>/', views.index, name='index_by_slug'),
    path('<slug:slug>/<int:id>/', views.product_detail, name='product_detail'),
]

shopproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('api/', include('api.urls', namespace='api')),
    path('order/', include('orders.urls', namespace='orders')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=40, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['slug']),
        ]


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    description = models.TextField()
    price = models.PositiveIntegerField()
    offer = models.DecimalField(max_digits=10, decimal_places=2)
    new_price = models.PositiveIntegerField(blank=True)
    weight = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    inventory = models.IntegerField(default=0)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'], name='-created'),
            models.Index(fields=['name'], name='name'),
        ]

    def __str__(self):
        return self.name


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    name = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='images/')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name if self.name else self.image

class ProductFeature(models.Model):
    feature_name = models.CharField(max_length=100)
    value = models.CharField(max_length=100)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='features')

    def __str__(self):
        return self.feature_name

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *


# Create your views here.

def index(request, category_slug=None):
    category = None
    products = Product.objects.all()
    categories = Category.objects.all()
    if category_slug:
        category = Category.objects.get(slug=category_slug)
        products = products.filter(category=category)

    context ={
        'category':category,
        'products':products,
        'category_slug':category_slug,
        'categories':categories,
    }
    return render(request, 'shop/product_list.html', context)


def product_detail(request, slug, id):
    product = get_object_or_404(Product, id=id, slug=slug)
    return render(request, 'shop/detail.html', {'product':product})

shop/templates/shop/detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}product datail{% endblock %}

{% block content %}
    {{ product.name }}
    <br>
    <img  style="height: 400px;width: auto;" src="{{ product.images.first.image.url }}">
    <h2>:ویژگی ها</h2>
    <ul>
        {% for feature in product.features.all %}
            <li>{{ feature }}</li>
        {% endfor %}
    </ul>
    <h3>توضیحات:</h3>
    {{ product.description }}
    <h5>موجودی:{{ product.inventory }}</h5>
    <br>
    <div>{{ product.new_price }} :قیمت</div>
    <br>
    <button type="button" class="add-cart" id="add-cart">
        <h4>افزودن به سبد خرید</h4>
    </button>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function(){
            $('#add-cart').click(function(){
                var button = $(this);
                $.ajax({
                   type: 'POST',
                   url: '{% url 'cart:add_to_cart' product.id %}',
                   data:{
                       'csrfmiddlewaretoken':'{{ csrf_token }}',
                   },
                   success: function(data) {
                       $('#item_count').text(data.item_count);
                       $('#total_price').text(data.total_price);
                    }
                });
            });
        });
    </script>


{% endblock %}

shop/templates/shop/product_list.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}product list{% endblock %}

{% block content %}

    {% if category %}
        <h1>لیست محصولات {{ category.name }}</h1>
    {% else %}
        <h1>لیست محصولات</h1>
    {% endif %}
    <br><br><br>
    <div class="category">
        <h2>دسته بندی ها</h2>
        <ul>
            <a href="{% url 'shop:index' %}"><li>All</li></a>
            {% for category in categories %}

                <a href="{% url 'shop:index_by_slug' category.slug %}"><li>{{ category.name }}</li></a>

            {% endfor %}
        </ul>

    </div>


    <div class="product-box">
            
        {% for product in products %}
            <a href="{% url 'shop:product_detail' product.slug product.id %}">
               <img style="height: 400px;width: auto;" src="{{ product.images.first.image.url }}">
                <br>
                {{ product.name }}
                <br>
                {% if product.offer %}
                    <div style="color: red;">{{ product.price }}</div>
                {% endif %}
                {{ product.new_price }}
            </a>
        {% endfor %}
        
    </div>

{% endblock %}